### ISSUE TITLE
질문있습니다 👋

### ISSUE THREAD

**Issue by ash-hun** [parkm2ngyu00/kkomiadventure#7]
@parkm2ngyu00 
 
안녕하세요 민규님, 최재훈입니다.
만드신 결과물 너무 잘봤어요. 코드 구경하다가 궁금한 점이 생겨서 이슈 남깁니다.

모델 구현하실 때 `tensorflow`와 `torch`를 동시에 활용하신 이유가 있을까요? 궁금하네요!

**Comment by mingyu-00** [comment]
@ash-hun 

재훈님 안녕하세요!

답변을 드리자면...
일단 수묵화 모델의 경우 저희가 직접 데이터셋을 활용해 P2GAN 모델을 사용해 구현하였는데, 카투나이즈와 캐릭터 변환의 경우는 그냥 오픈소스를 가져다 쓴 것입니다! 두 모델이 다른 라이브러리를 사용하다 보니 그렇게 되었네요 ㅎㅎ

답변이 되셨을까요??

**Comment by ash-hun** [comment]
아..! 기술스택의 선정에 뭔가 특별한 이유가 있을거라 생각해서 이슈를 남긴거였는데 그런건 아니었군요ㅋㅋㅋㅋㅋㅋ
잘 만드셨네요 😁😁 답변 감사합니당~
